<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_690566b07ca85',
	'title' => 'Participant Application Info',
	'fields' => array(
		array(
			'key' => 'field_69f03b3186518',
			'label' => 'Exhibitors',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_690566b041964',
			'label' => 'Exhibitor Space Applications',
			'name' => 'app',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Not all application types are need by all events.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_697d2ee7de12e',
					'label' => 'Next Event Waitlist/Newsletter',
					'name' => 'ex_news_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_ex_news',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd9ca6421fc',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f39bd638e44',
					'label' => 'Exhibitor/Vendor Booths',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'ie: Merchent Vendor',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 1,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_69f3c411b0853',
					'label' => 'Exhibitor/Vendor Icon',
					'name' => 'ex_ico',
					'aria-label' => '',
					'type' => 'icon_picker',
					'instructions' => '[app_ex_ico] </br>
For More Icons: https://fonts.google.com/icons. Copy \'Icon_name\' and add to icons.php',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'tabs' => array(
						0 => 'google',
					),
					'return_format' => 'array',
					'allow_in_bindings' => 1,
					'library' => 'all',
					'default_value' => array(
						'type' => NULL,
						'value' => NULL,
					),
				),
				array(
					'key' => 'field_6908f682debb9',
					'label' => 'Exhibitor/Vendor Status',
					'name' => 'ex_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'app_ex_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Appy SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6908f6c0debba',
					'label' => 'Exhibitor/Vendor Link',
					'name' => 'ex_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_ex_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69f39dbea2198',
					'label' => 'Exhibitor/Vendor Waitlist',
					'name' => 'ex_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_ex_wait',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69f39db1a2194',
					'label' => 'Cosplay Alley Booths',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'ie: Merchent Vendor',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_69f39db4a2195',
					'label' => 'Cosplay Icon',
					'name' => 'cos_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-book-open-reader fa-fw"&gt;&lt;/i&gt; Book Open Reader',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "store", "label" : "Store", "unicode" : "f54e"}',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_69f39db7a2196',
					'label' => 'Cosplay Alley Status',
					'name' => 'cos_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'app_cos_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Appy SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_69f3a3af6c41e',
					'label' => 'Cosplay Alley Link',
					'name' => 'cos_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => 'app_cos_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69cd89e5d9b9f',
					'label' => 'Cosplay Alley Waitlist',
					'name' => 'cos_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_ex_wait',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69f39ca338e4a',
					'label' => 'Accordian END',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'Comic Creator & 2D Artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 1,
				),
				array(
					'key' => 'field_69f39dcfa2199',
					'label' => 'Accordian END (copy)',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'Comic Creator & 2D Artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 1,
				),
				array(
					'key' => 'field_69c572df54c45',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69cd8f697752d',
					'label' => 'Artist Alley BOOTH',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'Comic Creator & 2D Artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_6971e5ba12c2c',
					'label' => 'Artist Alley BOOTH Icon',
					'name' => 'art_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => 'app_art_icon',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-book-open-reader fa-fw"&gt;&lt;/i&gt; Book Open Reader',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "palette", "label" : "Palette", "unicode" : "f53f"}',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_6908f75edebbd',
					'label' => 'Artist Alley BOOTH Status',
					'name' => 'art_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'app_art_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Coming SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6908f786debbe',
					'label' => 'Artist Alley BOOTH Link',
					'name' => 'art_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_art_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd89d5d9b9e',
					'label' => 'Artist Alley BOOTH Waitlist',
					'name' => 'art_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_art_wait',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd8f887752e',
					'label' => 'Artist Alley TABLE',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_69cd8fbd77531',
					'label' => 'Artist Alley TABLE Icon',
					'name' => 'art_tbl_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-book-open-reader fa-fw"&gt;&lt;/i&gt; Book Open Reader',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "palette", "label" : "Palette", "unicode" : "f53f"}',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_69cd8fdc77532',
					'label' => 'Artist Alley TABLE Status',
					'name' => 'art_tbl_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Coming SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_69cd8fe477533',
					'label' => 'Artist Alley TABLE Link',
					'name' => 'art_tbl_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_art_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd8fee77534',
					'label' => 'Artist Alley TABLE Waitlist',
					'name' => 'art_tbl_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'app_art_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd8f967752f',
					'label' => 'Artist Alley END',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 1,
				),
				array(
					'key' => 'field_69cd875c0f13e',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f39bfa38e45',
					'label' => 'Artisan Crafters',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'incudes 3D Artists',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 1,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_6971e59912c2b',
					'label' => 'Artisan Crafter Icon',
					'name' => 'ind_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-book-open-reader fa-fw"&gt;&lt;/i&gt; Book Open Reader',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "store", "label" : "Store", "unicode" : "f54e"}',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'allow_in_bindings' => 1,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_6908f6fadebbc',
					'label' => 'Artisan Crafter Status',
					'name' => 'ind_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6908fbd1b9536',
					'label' => 'Artisan Crafter Link',
					'name' => 'ind_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69cd89c0d9b9d',
					'label' => 'Artisan Crafter Waitlist',
					'name' => 'ind_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f39c7b38e48',
					'label' => 'Accordian END',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'Comic Creator & 2D Artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 1,
				),
				array(
					'key' => 'field_69f39c2638e46',
					'label' => 'Authors & Publishers',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'Comic Creator & 2D Artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 1,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'field_6971e5f112c2d',
					'label' => 'Author/Publisher Icon',
					'name' => 'lit_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-book-open-reader fa-fw"&gt;&lt;/i&gt; Book Open Reader',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "book-open-reader", "label" : "Book Open Reader", "unicode" : "f5da"}',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_69cd8935d9b99',
					'label' => 'Author/Publisher Status',
					'name' => 'lit_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_69cd893ad9b9a',
					'label' => 'Author/Publisher Link',
					'name' => 'lit_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69cd89a8d9b9c',
					'label' => 'Author/Publisher Waitlist',
					'name' => 'lit_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f39c9c38e49',
					'label' => 'Accordian END',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => 'Comic Creator & 2D Artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 1,
				),
				array(
					'key' => 'field_69cd887af9286',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_69f03c62fe1d8',
			'label' => 'Exhibitor Information Packets',
			'name' => 'info',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Links created by Web Dev as needed. Use this section to manage all outgoing links/docs across all websites.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69f042179c385',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f041760b635',
					'label' => 'Exhibitor Package Status',
					'name' => 'exhibitor_package_status_',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69f042209c386',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f03d510b634',
					'label' => 'Exhibitor Package PDF/ Published Google Doc Link',
					'name' => 'ex_pkg_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => 'info_ex_pkg_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69f03cca0b633',
					'label' => 'Exhibitor Booth Breakdown (Chart) Link',
					'name' => 'booth_chrt_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '[info_booth_chrt_url] </br>
For Published Google Doc of Exhibitor Packages Chart',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69f042309c387',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_69f03b3fc8147',
			'label' => 'Panelists',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6908fa1692c4f',
			'label' => 'Panelist/Guest Applications',
			'name' => 'app',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_697d2edfde12d',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69c5734654c46',
					'label' => 'Programming Icon',
					'name' => 'prog_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-book-open-reader fa-fw"&gt;&lt;/i&gt; Book Open Reader',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "store", "label" : "Store", "unicode" : "f54e"}',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_690567df41965',
					'label' => 'Panel Programming',
					'name' => 'pan_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6905688241966',
					'label' => 'Panel Programming Link',
					'name' => 'pan_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd8a81e2051',
					'label' => 'Panel Programming Waitlist',
					'name' => 'pan_wait',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_697d2f1373e5b',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6908fa3692c50',
					'label' => 'Cosplay Judge/Host',
					'name' => 'cos_judge_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6908faa392c51',
					'label' => 'Cosplay Juge/Host Link',
					'name' => 'cos_judge_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_697d2f1b73e5c',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6908fcb3ad734',
					'label' => 'Cosplay Contestant',
					'name' => 'cos_con_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status',
					'append' => '',
				),
				array(
					'key' => 'field_6908fd0bad735',
					'label' => 'Cosplay Contestant Link',
					'name' => 'cos_con_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd8b4e0d084',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6908fb45b9535',
					'label' => 'Special Guest',
					'name' => 'sp_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => 'Status',
					'append' => '',
				),
				array(
					'key' => 'field_6908fc7e9196e',
					'label' => 'Special Guest Link',
					'name' => 'sp_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_697d2f1d73e5d',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_69f03b43c8148',
			'label' => 'Media Partners & Sponsors',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6908fc1f9196d',
			'label' => 'Media/Partner Applications',
			'name' => 'app',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_697d2f4673e5e',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6908fe83a23f5',
					'label' => 'Press Pass',
					'name' => 'press_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6908febfa23f6',
					'label' => 'Press Pass Link',
					'name' => 'press_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_697d2f4e73e5f',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6908feed75e00',
					'label' => 'Convention Crew',
					'name' => 'crew_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'Apply SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Apply Soon',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_697d3397e63c8',
					'label' => 'Convention Crew Link',
					'name' => 'crew_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69cd8bfdb827c',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6908fdd0a23f3',
					'label' => 'Sponsors',
					'name' => 'spon_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'Get More Info',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Get More Info',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'key' => 'field_6908fe5da23f4',
					'label' => 'Sponsors Link',
					'name' => 'spon_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69cd8c0db827d',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_697d35fe77650',
					'label' => 'Sponsorship Deck PDF',
					'name' => 'spon_deck',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_697d2f5173e60',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'participant-info',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Applications & Info for vendors, panelists, etc',
	'show_in_rest' => 1,
	'display_title' => 'Participant/Partner Info - Options Page',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'options-pages' => 'Options Pages',
		'people' => 'People',
	),
	'modified' => 1777590967,
));

endif;