<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69093bcaccc1f',
	'title' => 'Notes & Reference',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69093bcbaf101',
			'label' => 'Notes/ Reference',
			'name' => 'note',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69093c05af102',
					'label' => 'Notes',
					'name' => 'pad',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Back-end notes for Back-end people',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => 'Put whatever you need here: shortcode, reminders, content you\'ll need later...',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69093c7caf103',
					'label' => 'Reference',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '[acf field="" post_id="options" ]',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'alerts',
			),
		),
		array(
			array(
				'param' => 'nav_menu',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'nav_menu',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'schedules-maps',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Dev Tool on Every post/page',
	'show_in_rest' => 0,
	'display_title' => 'Notes Feature on the side',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'qef_simple_location_rules' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'dev' => 'Dev',
	),
	'modified' => 1765912243,
));

endif;