<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6909055819b18',
	'title' => 'Products - Tickets/ Photo Ops',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690fbf9559074',
			'label' => 'Tickets',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6909055802b30',
			'label' => 'Ticket Links & Status',
			'name' => 'tkt',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690fbfe1df8e4',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_693e61d97df71',
					'label' => 'Ticket Icon',
					'name' => 'ico',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-images fa-fw"&gt;&lt;/i&gt; Images',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "ticket", "label" : "Ticket", "unicode" : "f145"}',
					'save_format' => 'element',
					'allow_null' => 1,
					'show_preview' => 1,
					'enqueue_fa' => 1,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909057d02b31',
					'label' => 'Ticket Sales Status',
					'name' => 'stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Tickets Available SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Tickets Available SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69276e9c11d29',
					'label' => 'Ticket Sales	- Call to Action',
					'name' => 'act',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_act',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'BUY NOW',
					'prepend' => 'Action:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_693a1b9eab7d4',
					'label' => 'Ticket Discount',
					'name' => 'dis',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_dis',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '30% off for a Limited Time',
					'prepend' => 'Discount:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690905b602b32',
					'label' => 'Main Shop Page Link (LEAP)',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690905d702b33',
					'label' => 'Ticket Sale Link- Weekend',
					'name' => 'wk_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_wk_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690906a402b34',
					'label' => 'Ticket Sales Link - Days',
					'name' => 'day_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_day_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690fc004df8e6',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690906ec02b35',
					'label' => 'Special Event Ticket Status',
					'name' => 'sp_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_sp_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Available SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'More Info SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909082002b36',
					'label' => 'Special Event Tickets Link',
					'name' => 'sp_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_sp_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909083b02b37',
					'label' => 'After Party Ticket Status',
					'name' => 'prt_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_prt_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'More Info SOON',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909087d02b38',
					'label' => 'After Party Ticket Link',
					'name' => 'prt_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_prt_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690fbfefdf8e5',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690fbfa559075',
			'label' => 'Ops/Autos Links & Status',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690908f202b39',
			'label' => 'Photo Ops/Autographs',
			'name' => 'celeb',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691bd31e40c6e',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_693e63307df72',
					'label' => 'Photo Op Icon',
					'name' => 'ops_ico',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => 'ops_ico',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-images fa-fw"&gt;&lt;/i&gt; Images',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "camera-retro", "label" : "Camera Retro", "unicode" : "f083"}',
					'save_format' => 'element',
					'allow_null' => 1,
					'show_preview' => 1,
					'enqueue_fa' => 1,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909093502b3a',
					'label' => 'Photo Ops Status',
					'name' => 'ops_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Coming SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Coming SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_692774437466e',
					'label' => 'Photo Ops - Call to Action',
					'name' => 'ops_act',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Buy NOW',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909096302b3b',
					'label' => 'Photo Ops Link - Friday',
					'name' => 'op_fri_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909099b02b3d',
					'label' => 'Photo Ops Link - Saturday',
					'name' => 'op_sat_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690909a802b3e',
					'label' => 'Photo Ops Link - Sunday/ Thursday',
					'name' => 'op_sun_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690909c902b3f',
					'label' => 'Group Photo Ops',
					'name' => 'grp_ops_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Coming SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Coming SOON',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690909f002b40',
					'label' => 'Group Photo Ops LInk',
					'name' => 'grp_ops_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691bd33140c6f',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_693e64157df74',
					'label' => 'Autograph Icon',
					'name' => 'auto_ico',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => 'auto_ico',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '&lt;i class="fa-classic fa-solid fa-images fa-fw"&gt;&lt;/i&gt; Images',
					'default_value' => '{"family" : "classic", "style" : "solid", "id" : "images", "label" : "Images", "unicode" : "f302"}',
					'save_format' => 'element',
					'allow_null' => 1,
					'show_preview' => 1,
					'enqueue_fa' => 1,
					'allow_in_bindings' => 1,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69090b2d3f1b4',
					'label' => 'Autographs',
					'name' => 'auto_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Purchase at Event',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Purchase at Event',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69090b883f1b5',
					'label' => 'Autographs Link',
					'name' => 'auto_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69090ba33f1b6',
					'label' => 'Celeb Row eXtras',
					'name' => 'row_xtra_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Purchase at Event',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Status:',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69090bd23f1b7',
					'label' => 'Celeb Row eXtras - Link',
					'name' => 'row_xtra_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
					),
					'taxonomy' => array(
					),
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69090c193f1b9',
					'label' => 'Celeb Row eXtras - Details',
					'name' => '_row_xtra_deet',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691bd34940c70',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'products',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Tickets. Autographs. Photo Ops. Special Events',
	'show_in_rest' => 1,
	'display_title' => 'Products Options Page',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'qef_simple_location_rules' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'products' => 'Products',
	),
	'modified' => 1765697901,
));

endif;