<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69091d610fde2',
	'title' => 'Guest Info - Options Page',
	'fields' => array(
		array(
			'key' => 'field_69e94bb5ff585',
			'label' => 'Guest Statuses',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69091d6174a9f',
			'label' => 'Guest Statuses',
			'name' => 'stat',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_691b93ae23b36',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69091d8574aa0',
					'label' => 'TV/Film',
					'name' => 'celeb',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_celeb',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'View List SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'Status:',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69091dc874aa1',
					'label' => 'Authors/Writers',
					'name' => 'author',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_author',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'View List SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69091de674aa2',
					'label' => 'Artists',
					'name' => 'artist',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_artist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'View List Soon',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_691b93b823b37',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69091e2574aa3',
					'label' => 'Comic Creators',
					'name' => 'comic',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_comic',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'View List SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69091e4174aa4',
					'label' => 'Featured Panelist',
					'name' => 'panelist',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_panelist',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'View List SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_691b9ebe2b671',
					'label' => 'Featured Cosplayers',
					'name' => 'cosplayer',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => 'Coming Soon',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69e94cb1935db',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
				array(
					'key' => 'field_69e94c2c700e0',
					'label' => 'Postponed Guest Default Message',
					'name' => 'postponed',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => 'stat_postponed',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '[page_title] unfortunately, canceled their appearance at the upcoming [acf field="event_title" post_id="options" ] due to scheduling conflicts. We are so sad they needed to postpone, but we hope to have them again in the near future!

If [page_title] had Photo Ops or Autographs that you pre-purchased, you have two options:

<strong>1. Upgrade or swap to another product.</strong>
You may upgrade or swap your photo op and/or group photo op with [page_title] to another guest appearing at the show. Service fees will apply. All transactions are final.

To upgrade your Voucher, open the Photo Op confirmation email that was sent to you from GrowTix, and view your order. Click the purple button that says “Upgrade” or the purple button that says “Swap”. A new window will appear with a drop-down list of eligible guests. Select the product you would like to upgrade or Swap to and pay the difference if applicable.

<em>Note: We highly recommend you bring a printed copy of the QR code for each Photo Op that you purchased.</em>

<strong>2. Issue yourself a self-service refund.</strong>
You may receive a full refund for the Photo Op and/or Group Photo Op with [page_title ]. <a href="[acf field=\'cs_leap_user_url\' post_id=\'options\']">Log in to your LEAP account</a> and view your order. You will see a red button below the [page_title ] Photo Op product that says “Refund Product”. Click “Refund Product”.

For more information,<a href="[acf field=\'cs_zen_url\' post_id=\'options\']">visit our Help Desk</a>',
					'allow_in_bindings' => 1,
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 1,
				),
			),
		),
		array(
			'key' => 'field_69e94bc48d8cc',
			'label' => 'Small Print/Footer Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c74394ea0a8',
			'label' => 'Guest/eXperience Footers',
			'name' => 'foo',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69099c2fa01e8',
					'label' => 'Small Print - Standard',
					'name' => 'small_print',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'foo_small_print',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '*Guest appearances are subject to change or cancellation.',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_69099c92a01e9',
					'label' => 'Celeb Small Print',
					'name' => 'celeb_small_print',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'foo_celeb_small_print',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '*Photo Op & Autograph experiences are subject to change.

**Photo Ops include one printed photo. Digital copies are available to purchase from our Photo Op Partners at the event. View the FAQ for more info

***Autographs include one 8x10 pre-printed photo - For more information about Autographs, Memorabilia Signings, Voice recordings, and other signing table opportunities visit the Celebrities Booth during the convention. Prices and options are subject to change. View FAQ for More Info',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 6,
					'placeholder' => '',
					'new_lines' => 'wpautop',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'guests-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'display_title' => 'Guests Lists Status Options Page',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1777316969,
	'acfe_categories' => array(
		'options-pages' => 'Options Pages',
		'people' => 'People',
	),
));

endif;