<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69093e0d83bdc',
	'title' => 'Posts',
	'fields' => array(
		array(
			'key' => 'field_690983c0576b4',
			'label' => 'Basic Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6909820ffcf2b',
			'label' => 'Basics/Categories',
			'name' => 'info',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_690994dc3e812',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69093e0d212c7',
					'label' => 'Featured Image',
					'name' => 'feat_img',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'return_format' => 'array',
					'library' => 'all',
					'acfe_thumbnail' => 1,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_690995593e817',
					'label' => 'Featured Info',
					'name' => 'feat',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Displays Below Featured Image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6909950a3e814',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_691fb32d72580',
					'label' => 'Post Display Order',
					'name' => 'display_order',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '<b>Celebrities:</b>100 | <b>Voice:</b> 200 | <b>Comics:</b> 300 | <b>Authors:</b> 400 | <b>Artists:</b> 500 | <b>Panelists/Vendors:</b> 600

<b>Special Events:</b> 1000 | <b>Features/Activities:</b> 2000 |	<b>Vehicles:</b> 4000 | <b>Vendors:</b> 5000',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'min' => '',
					'max' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69093efbfcf29',
					'label' => 'Main Cat',
					'name' => 'main_cat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_691fa14a8775e',
					'label' => 'Guest List',
					'name' => 'guest_list',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => 'info_guest_list',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'guest-list',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69423abd00ab9',
					'label' => 'Post Categories (Blog ONLY)',
					'name' => 'post_cat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'blog',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_6909950e3e815',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_69795c5e3bb11',
			'label' => 'Guest eXperiences',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'key' => 'field_69795c743bb12',
			'label' => 'Guest Xperiences/Statuses',
			'name' => 'xp',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69795c743bb21',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795c743bb2b',
					'label' => 'Days Appearing',
					'name' => 'days',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 1,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'days',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb2a',
					'label' => 'Fandoms',
					'name' => 'fandom',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 0,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'fandoms',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb27',
					'label' => 'eXperiences',
					'name' => 'xp',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'xp',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'allow_quickedit' => 1,
					'allow_bulkedit' => 1,
					'show_column_filter' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb28',
					'label' => 'eXperience Status',
					'name' => 'xp_stat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 1,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'xp-status',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb24',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795db83bb31',
					'label' => 'Autograph Price',
					'name' => 'auto_price',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => 1,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69795d253bb30',
					'label' => 'Photo Op Price',
					'name' => 'op_price',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => 1,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69795e003bb32',
					'label' => 'Photo Ops Link',
					'name' => 'op_url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'https://checkout.conventions.leapevent.tech/eh/FanX_Salt_Lake_Comic_Convention_2026/56121?cc=autos',
					'acfe_settings' => array(
						'69ceff45c8718' => array(
							'acfe_settings_location' => '',
							'acfe_settings_settings' => array(
								'69ceff49c8719' => array(
									'acfe_settings_setting_type' => 'required',
									'acfe_settings_setting_operator' => 'true',
								),
							),
						),
					),
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69795c743bb29',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795e4c3bb33',
					'label' => 'Group Photo Ops Involved in:',
					'name' => 'group_op',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => array(
						0 => 'products',
					),
					'post_status' => '',
					'taxonomy' => array(
						0 => 'xp:group-photo-ops',
					),
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 1,
					'save_post_type' => 'post',
					'save_post_status' => 'draft',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_null' => 0,
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795f3b781ca',
					'label' => 'Celebrity Row Extras',
					'name' => 'celeb_extras',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69795c743bb2c',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795c743bb2f',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_690983ea576b5',
			'label' => 'Header/Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6909843a576b6',
			'label' => 'Header/ Footer Info',
			'name' => 'heafoo',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69098285576b2',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Displays Subtitle Below Post Name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_690982b5576b3',
					'label' => 'Subtext',
					'name' => 'subtext',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Block of Text below Subtitle',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69c7420d968df',
					'label' => 'Footer Smallprint Update',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'to streamline all smallprint changes, you can now find the smallprint content on the Guests Option Page. For induvidual updates talk to the Dev about',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
					'acfe_settings' => '',
					'acfe_permissions' => '',
				),
			),
		),
		array(
			'key' => 'field_6909850a576b7',
			'label' => 'Galleries',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6909858c576b8',
			'label' => 'Featured Posts/ Image Galleries',
			'name' => 'gal',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69098f37576bd',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '4/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69098604576b9',
					'label' => 'Multi-Post Gallery - Title',
					'name' => 'multi_post_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_690a55326b260',
					'label' => 'Multi-Post Gallery - Subtitle',
					'name' => 'multi_post_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 3,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_690986b7576ba',
					'label' => 'Mutli-Post Gallery - Post IDs',
					'name' => 'multi_post_ids',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => array(
						0 => 'post',
						1 => 'guests',
						2 => 'partner',
						3 => 'product',
						4 => 'feature',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'key' => 'field_69098b62576bb',
					'label' => 'Featured Post - Title',
					'name' => 'feat_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_690a5498f560e',
					'label' => 'Featured Post - Subtitle',
					'name' => 'feat_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69098f00576bc',
					'label' => 'Featured Post - Post ID',
					'name' => 'feat_post_id',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'post_type' => array(
						0 => 'post',
						1 => 'partner',
						2 => 'guests',
						3 => 'feature',
						4 => 'product',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_null' => 0,
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'key' => 'field_69098f67576be',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'columns' => '8/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69098f99576c0',
					'label' => 'Dynamic Gallery Title',
					'name' => 'dyn_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_690a54c9f560f',
					'label' => 'Dynamic Gallery Subtitle',
					'name' => 'dyn_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69098fcb576c1',
					'label' => 'Dynamic Gallery Images',
					'name' => 'dyn_img',
					'aria-label' => '',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'return_format' => 'array',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'insert' => 'append',
					'preview_size' => 'thumbnail',
				),
				array(
					'key' => 'field_69098f8a576bf',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_6942422263f78',
			'label' => 'Schedule/ Location',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6942422f63f79',
			'label' => 'Schedule',
			'name' => 'sched',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'key' => 'field_69979d07220e2',
			'label' => 'Location',
			'name' => 'loca',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69979d48220e3',
					'label' => 'Address',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69979dfa220e4',
					'label' => 'Map',
					'name' => 'map',
					'aria-label' => '',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => 300,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_in_bindings' => 0,
				),
			),
		),
		array(
			'key' => 'field_694265bfb3f83',
			'label' => 'Buttons / Links',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69705d543efc4',
			'label' => 'Buttons',
			'name' => 'button',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69706e537ffb9',
					'label' => 'Button Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69705d543efc4',
				),
				array(
					'key' => 'field_69706e777ffba',
					'label' => 'Button Subtext',
					'name' => 'subtext',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69705d543efc4',
				),
				array(
					'key' => 'field_69706e8a7ffbb',
					'label' => 'Button Link',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69705d543efc4',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'features',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'guests',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'partner',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'products',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'venue',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Posts & Profiles - Temporary',
	'show_in_rest' => 0,
	'display_title' => 'Posts - [Temporary Template]',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1776313107,
	'acfe_categories' => array(
		'people' => 'People',
		'posts' => 'Posts',
	),
));

endif;