<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69093e0d83bdc',
	'title' => 'Guest Profile Pages',
	'fields' => array(
		array(
			'key' => 'field_690983c0576b4',
			'label' => 'Basic Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6909820ffcf2b',
			'label' => 'Basics/Categories',
			'name' => 'info',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_690994dc3e812',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69093e0d212c7',
					'label' => 'Featured Image',
					'name' => 'feat_img',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1,
					'show_column_sortable' => false,
					'uploader' => '',
					'return_format' => 'array',
					'library' => 'all',
					'acfe_thumbnail' => 1,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 1,
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_690995593e817',
					'label' => 'Featured Info',
					'name' => 'feat',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Displays Below Featured Image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_690994ea3e813',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_691fb32d72580',
					'label' => 'Post Display Order',
					'name' => 'display_order',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '<b>Celebrities:</b>Top 100 | <b>Voice:</b> 200 | Vend Celebs: 290 <b>Comics:</b> 300 | <b>Authors:</b> 400 | <b>Artists:</b> 500 | <b>Panelists/Vendors:</b> 600',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'min' => '',
					'max' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69093efbfcf29',
					'label' => 'Main Cat',
					'name' => 'main_cat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 0,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'category',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_691fa14a8775e',
					'label' => 'Guest List',
					'name' => 'guest_list',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => 'info_guest_list',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'guest-list',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69fa640081616',
					'label' => 'Announcements & Updates Included in:',
					'name' => 'feat_updates',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '[info_feat_updates] </br>
Automatically populates when a Blog Post Features this Profile in an Announcement or Update.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
					),
					'post_status' => '',
					'taxonomy' => array(
						0 => 'blog:event-updates-announcements',
					),
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => true,
						'acfe_bidirectional_related' => array(
							0 => 'field_69fa7465a763d',
							1 => 'field_69fa774448d6d',
							2 => 'field_6a039ab5557f3',
							3 => 'field_6a039ab5557fa',
							4 => 'field_6a17c496f9dd9',
							5 => 'field_69fa7465a7904',
						),
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'key' => 'field_6909950e3e815',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_69795c5e3bb11',
			'label' => 'Guest eXperiences',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'key' => 'field_69795c743bb12',
			'label' => 'Guest Xperiences/Statuses',
			'name' => 'xp',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69795c743bb21',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795c743bb2b',
					'label' => 'Days Appearing',
					'name' => 'days',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 1,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'days',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb2a',
					'label' => 'Fandoms',
					'name' => 'fandom',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 0,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'fandoms',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb27',
					'label' => 'eXperiences',
					'name' => 'xp',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'xp',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'allow_quickedit' => 1,
					'allow_bulkedit' => 1,
					'show_column_filter' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb28',
					'label' => 'eXperience Status',
					'name' => 'xp_stat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => 1,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'taxonomy' => 'xp-status',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'key' => 'field_69795c743bb24',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795db83bb31',
					'label' => 'Autograph Price',
					'name' => 'auto_price',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => 1,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69795d253bb30',
					'label' => 'Photo Op Price',
					'name' => 'op_price',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => 1,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69795e003bb32',
					'label' => 'Photo Ops Link',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Currently pulls Friday link from Guest Options Page.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
					'acfe_settings' => '',
					'acfe_permissions' => '',
				),
				array(
					'key' => 'field_69fd0d48e7eb8',
					'label' => 'Dedicated Product Category Link',
					'name' => 'ded_prod_cat',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '<p>[xp_ded_prod_cat] Use when a guest has their own product category in the shop</p>
<i>*Currently replaces the Photo Op, Autograph links on their profile, and adds a link to the Celebrity Row eXtras status, when said products are on sale</i>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'key' => 'field_69795c743bb29',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_69795e4c3bb33',
					'label' => 'Group Photo Ops Involved in:',
					'name' => 'group_op',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '[xp_group_op] </br>
Automatically populates when Group Photo Op Product is pushed live.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69795c743bb2a',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'products',
					),
					'post_status' => '',
					'taxonomy' => array(
						0 => 'xp:group-photo-ops',
					),
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => true,
						'acfe_bidirectional_related' => array(
							0 => 'field_69fa774569713',
						),
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
					'save_post_status' => '',
				),
				array(
					'key' => 'field_6a039d348ee12',
					'label' => 'Featured in (eXperiences):',
					'name' => 'vend_booth',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '[xp_vend_booth] </br>
Automatically populates when added to a Feature/Activity profile page.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'features',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '1',
						'acfe_bidirectional_related' => array(
							0 => 'field_69fa7465a763d',
						),
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'key' => 'field_69795f3b781ca',
					'label' => 'Celebrity Row Extras',
					'name' => 'celeb_extras',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69795c743bb2f',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_690983ea576b5',
			'label' => 'Header/Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6909843a576b6',
			'label' => 'Header/ Footer Info',
			'name' => 'heafoo',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69098285576b2',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Displays Subtitle Below Post Name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_690982b5576b3',
					'label' => 'Subtext',
					'name' => 'subtext',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Block of Text below Subtitle',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69e7f1c87f3b2',
					'label' => 'Footer Smallprint Update',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'to streamline all smallprint changes, you can now find the smallprint content on the Guests Option Page. For induvidual updates talk to the Dev about',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
					'acfe_settings' => '',
					'acfe_permissions' => '',
				),
			),
		),
		array(
			'key' => 'field_6942422263f78',
			'label' => 'Schedule/ Location',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a03999f6c4b3',
			'label' => 'Schedule & Room/Booth',
			'name' => 'sched',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_6a03a4069c109',
					'label' => 'Room/Booth Number',
					'name' => 'room_booth',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '[sched_room_booth]',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6a1b302c41258',
					'label' => 'Guest Schedule',
					'name' => 'guest',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => 'The content here appears in the schedule tab when there is no events in the leap schedule. 
If guest shares a schedule, post it here.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '[page_title] doesn\'t have a schedule posted here.
Stop by [acf field="sched_room_booth"] to see what they\'re up to!',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 1,
				),
				array(
					'key' => 'field_6a1e73aeaaf41',
					'label' => 'Guest eXperiences',
					'name' => 'guest_xp',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '[sched_guest_xp]
The content here appears in the eXperience tab when there is no eXperiences chosen, or the chosen eXperience doesn\'t need featuring. Add feature/activity info here that is in addition to bio.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 1,
				),
			),
		),
		array(
			'key' => 'field_6a17d6bcc82b4',
			'label' => 'Galleries & Featured Posts',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a17c496f9dc2',
			'label' => 'Featured Posts/ Image Galleries',
			'name' => 'gal',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_6a17c496f9dcd',
					'label' => 'Featured Profiles	- Multi-Post Gallery',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 1,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_permissions' => '',
				),
				array(
					'key' => 'field_6a17c496f9dce',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6a17c496f9dcf',
					'label' => 'Featured Profiles Multi-Post Gallery - Title',
					'name' => 'multi_post_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6a17c496f9dd0',
					'label' => 'Featured Profiles - Multi-Post Gallery - Subtitle',
					'name' => 'multi_post_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => 3,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6a17c496f9dd1',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '8/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6a17c496f9dd2',
					'label' => 'Featured Profiles - Mutli-Post Gallery - Post IDs',
					'name' => 'multi_post_ids',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '[gal_multi_post_ids]',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'guests',
						1 => 'partner',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '1',
						'acfe_bidirectional_related' => '',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'key' => 'field_6a17c496f9dd3',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
				array(
					'key' => 'field_6a17c496f9dd4',
					'label' => 'Featured Post Gallery',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_permissions' => '',
				),
				array(
					'key' => 'field_6a17c496f9dd5',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6a17c496f9dd6',
					'label' => 'Featured Post - Title',
					'name' => 'feat_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6a17c496f9dd7',
					'label' => 'Featured Post - Subtitle',
					'name' => 'feat_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6a17c496f9dd8',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '8/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6a17c496f9dd9',
					'label' => 'Featured Post- Post ID',
					'name' => 'feat_post_id',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
						1 => 'partner',
						2 => 'guests',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => true,
						'acfe_bidirectional_related' => array(
							0 => 'field_69fa640081616',
						),
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'key' => 'field_6a17c496f9dda',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
				array(
					'key' => 'field_6a17c496f9ddb',
					'label' => 'Dynamic Gallery (Images)',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_permissions' => '',
				),
				array(
					'key' => 'field_6a17c496f9ddc',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6a17c496f9ddd',
					'label' => 'Dynamic Gallery Title',
					'name' => 'dyn_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_6a17c496f9dde',
					'label' => 'Dynamic Gallery Subtitle',
					'name' => 'dyn_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_6a17c496f9ddf',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '8/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'key' => 'field_6a17c496f9de0',
					'label' => 'Dynamic Gallery Images',
					'name' => 'dyn_img',
					'aria-label' => '',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_permissions' => '',
					'insert' => 'append',
					'preview_size' => 'thumbnail',
				),
				array(
					'key' => 'field_6a17c496f9de1',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'key' => 'field_69979d07220e2',
			'label' => 'Location',
			'name' => 'loca',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'key' => 'field_69979d48220e3',
					'label' => 'Address',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69979dfa220e4',
					'label' => 'Map',
					'name' => 'map',
					'aria-label' => '',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => 300,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_in_bindings' => 0,
				),
			),
		),
		array(
			'key' => 'field_694265bfb3f83',
			'label' => 'Buttons / Links',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69705d543efc4',
			'label' => 'Buttons',
			'name' => 'button',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69706e537ffb9',
					'label' => 'Button Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69705d543efc4',
				),
				array(
					'key' => 'field_69706e777ffba',
					'label' => 'Button Subtext',
					'name' => 'subtext',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69705d543efc4',
				),
				array(
					'key' => 'field_69706e8a7ffbb',
					'label' => 'Button Link',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69705d543efc4',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'guests',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'partner',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => 'Guest Profile Pages',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe' => array(
		'autosync' => array(
			0 => 'php',
			1 => 'json',
		),
		'advanced' => '1',
	),
	'modified' => 1781628590,
	'acfe_categories' => array(
		'people' => 'People',
		'posts' => 'Posts',
		'profile-pages' => 'Profile Pages',
	),
));

endif;