<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_690921e979285',
	'title' => 'Theme & Web Development',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690e4380f2550',
			'label' => 'Branding',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690e43a5f2551',
			'label' => 'Color Palette',
			'name' => 'color',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e7cf98de21',
					'label' => 'Color Palete Info',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'New Color Picker options must be registered in the FanX Theme Functions file. 
Proceed with Caution: Changing this color palette will affect the colors on the website. 
prepend: color_',
					'new_lines' => 'br',
					'esc_html' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e574c88b73',
					'label' => '(Column 2/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '2/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e63ee66891',
					'label' => 'Color Swatches - Dark',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e550bf2556',
					'label' => 'Main Color - Dark',
					'name' => 'drk',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'drk',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e49f1f2552',
					'label' => 'Base Color - Dark',
					'name' => 'base',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'base',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e54cdf2555',
					'label' => 'Primary Color - Dark',
					'name' => 'prim',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'prim',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e5a75f4537',
					'label' => 'Accent Color - Dark',
					'name' => 'acc',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'acc',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e575988b74',
					'label' => '(Column 2/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '2/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e63c066890',
					'label' => 'Color Swatches - Light',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e4b9ef2553',
					'label' => 'Main Color - Light',
					'name' => 'lght',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'lght',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e5c7fe6024',
					'label' => 'Base Color - Light',
					'name' => 'base_lght',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'base_lght',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e5c88e6025',
					'label' => 'Primary Color - Light',
					'name' => 'prim_lght',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'prim_lght',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e5561f2557',
					'label' => 'Accent Color - Light',
					'name' => 'acc_lght',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'acc_lght',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 1,
					'palette_colors' => '',
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e60166688c',
					'label' => '(Column 2/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '2/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691e62540863b',
					'label' => 'Color Swatches - Bright',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691e74941dbcf',
					'label' => 'Main Color - Bright',
					'name' => 'brht',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'brht',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691e68eb8051d',
					'label' => 'Base Color - Bright',
					'name' => 'base_brht',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'base_brht',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691e713d6bc3b',
					'label' => 'Primary Color - Bright',
					'name' => 'prim_brht',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'prim_brht',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_691e7e957f9e3',
					'label' => 'Accent Color - Bright',
					'name' => 'acc_brht',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'prim_brht',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e90a4d5bb1',
					'label' => '(Column 2/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '2/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e8e3136584',
					'label' => 'Font Colors',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e8e2b36583',
					'label' => 'Basic White',
					'name' => 'fnt_wht',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'fnt_wht',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 1,
					'palette_colors' => '',
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e8eaa36585',
					'label' => 'True Black',
					'name' => 'fnt_blk',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'fnt_blk',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 1,
					'palette_colors' => '',
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e8e1f36582',
					'label' => '(Column 2/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '2/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690e576188b75',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690e4303f254c',
			'label' => 'Add Code/Hooks',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690921e913f35',
			'label' => 'Theme Code Integration',
			'name' => 'theme',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_696ff529595e3',
					'label' => '',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'For Customer Service integrations (ie: Chatbot) fields are located on the Customer Service Options Page.',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909232613f36',
					'label' => 'Head Code',
					'name' => 'head',
					'aria-label' => '',
					'type' => 'acfe_code_editor',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'mode' => 'text/x-php',
					'lines' => 1,
					'indent_unit' => '',
					'maxlength' => '',
					'rows' => 8,
					'max_rows' => '',
					'return_format' => array(
					),
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6909239d13f38',
					'label' => 'Body Code',
					'name' => 'body',
					'aria-label' => '',
					'type' => 'acfe_code_editor',
					'instructions' => 'For Facebook Tags, Google Analytics, etc',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'mode' => 'text/x-php',
					'lines' => 1,
					'indent_unit' => '',
					'maxlength' => '',
					'rows' => 8,
					'max_rows' => '',
					'return_format' => array(
					),
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_690923bf13f39',
					'label' => 'Footer Code',
					'name' => 'footer',
					'aria-label' => '',
					'type' => 'acfe_code_editor',
					'instructions' => 'For Facebook Tags, Google Analytics, etc',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'mode' => 'text/x-php',
					'lines' => 1,
					'indent_unit' => '',
					'maxlength' => '',
					'rows' => 8,
					'max_rows' => '',
					'return_format' => array(
					),
					'allow_in_bindings' => 1,
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_690e435df254e',
			'label' => 'ADA/ Accessibility',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6909248081a24',
			'label' => 'Web Accessibility',
			'name' => 'wa',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'dev',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'display_title' => 'Website Development',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'qef_simple_location_rules' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'dev' => 'Dev',
	),
	'modified' => 1768945665,
));

endif;