<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69fa746487ed1',
	'title' => 'Blog Posts',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648f975',
			'label' => 'Basic Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648f9ae',
			'label' => 'Basics/Categories',
			'name' => 'info',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d40e',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d44b',
					'label' => 'Featured Image',
					'name' => 'feat_img',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'return_format' => 'array',
					'library' => 'all',
					'acfe_thumbnail' => 1,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 1,
					'preview_size' => 'medium',
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d484',
					'label' => 'Featured Info',
					'name' => 'feat',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Displays Below Featured Image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'rows' => 4,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d4bc',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => 1,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 100,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d52e',
					'label' => 'Main Cat',
					'name' => 'main_cat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d5d7',
					'label' => 'Post Categories',
					'name' => 'post_cat',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '[info_post_cat]',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'blog',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa74649d610',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648f9e7',
			'label' => 'Guest eXperiences',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fa1f',
			'label' => 'Guest Xperiences/Statuses (Update for EVENTS)',
			'name' => 'xp',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa746512c4c',
					'label' => '(Column 3/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '3/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => 0,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa746512cbf',
					'label' => 'Fandoms',
					'name' => 'fandom',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'fandoms',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => 1,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 1,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa746512cf8',
					'label' => 'eXperiences',
					'name' => 'xp',
					'aria-label' => '',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'xp',
					'add_term' => 1,
					'save_terms' => 1,
					'load_terms' => 1,
					'return_format' => 'id',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => '0',
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'multiple' => 0,
					'bidirectional_target' => array(
					),
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa746512f2d',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fa58',
			'label' => 'Header/Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fa91',
			'label' => 'Header/ Footer Info',
			'name' => 'heafoo',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 1,
					'allow_quickedit' => 1,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa7465845cb',
					'label' => 'Subtitle',
					'name' => 'subtitle',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Displays Subtitle Below Post Name',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa746584607',
					'label' => 'Subtext',
					'name' => 'subtext',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'Block of Text below Subtitle',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa74658463f',
					'label' => 'Footer Smallprint Update',
					'name' => '',
					'aria-label' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'to streamline all smallprint changes, you can now find the smallprint content on the Guests Option Page. For induvidual updates talk to the Dev about',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
					'acfe_settings' => '',
					'acfe_permissions' => '',
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fac9',
			'label' => 'Featured Posts/Galleries',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6a039ab5557e3',
			'label' => 'Featured Posts/ Image Galleries',
			'name' => 'gal',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557ee',
					'label' => 'Featured Profiles	- Multi-Post Gallery',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 1,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_permissions' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557ef',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f0',
					'label' => 'Featured Profiles Multi-Post Gallery - Title',
					'name' => 'multi_post_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f1',
					'label' => 'Featured Profiles - Multi-Post Gallery - Subtitle',
					'name' => 'multi_post_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => 3,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f2',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '8/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f3',
					'label' => 'Featured Profiles - Mutli-Post Gallery - Post IDs',
					'name' => 'multi_post_ids',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '[gal_multi_post_ids]
Will ALSO add this post to the announcement section of all profiles selected.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'guests',
						1 => 'features',
						2 => 'partner',
						3 => 'products',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => true,
						'acfe_bidirectional_related' => array(
							0 => 'field_69fa774448d6d',
							1 => 'field_69fa640081616',
							2 => 'field_6a03999f79446',
						),
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f4',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f5',
					'label' => 'Featured Post Gallery',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_permissions' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f6',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f7',
					'label' => 'Featured Post - Title',
					'name' => 'feat_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f8',
					'label' => 'Featured Post - Subtitle',
					'name' => 'feat_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557f9',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '8/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557fa',
					'label' => 'Featured Post- Post ID',
					'name' => 'feat_post_id',
					'aria-label' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'post',
						1 => 'partner',
						2 => 'guests',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'id',
					'multiple' => 1,
					'save_custom' => 0,
					'save_post_status' => 'publish',
					'acfe_bidirectional' => array(
						'acfe_bidirectional_enabled' => true,
						'acfe_bidirectional_related' => array(
							0 => 'field_69fa640081616',
						),
					),
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_null' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'save_post_type' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557fb',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557fc',
					'label' => 'Dynamic Gallery (Images)',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_permissions' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557fd',
					'label' => '(Column 4/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '4/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557fe',
					'label' => 'Dynamic Gallery Title',
					'name' => 'dyn_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab5557ff',
					'label' => 'Dynamic Gallery Subtitle',
					'name' => 'dyn_sub',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'acfe_permissions' => '',
					'allow_in_bindings' => 1,
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab555800',
					'label' => '(Column 8/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '8/12',
					'endpoint' => 0,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab555801',
					'label' => 'Dynamic Gallery Images',
					'name' => 'dyn_img',
					'aria-label' => '',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_permissions' => '',
					'insert' => 'append',
					'preview_size' => 'thumbnail',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6a039ab555802',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'acfe_permissions' => '',
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fb3a',
			'label' => 'Schedule/ Location',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fbb0',
			'label' => 'Remote Location',
			'name' => 'loca',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6ac00c71cf656',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa7466a3867',
					'label' => 'Address',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_settings' => '',
					'acfe_validate' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6ac00c83cf657',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa7466a38a3',
					'label' => 'Map',
					'name' => 'map',
					'aria-label' => '',
					'type' => 'google_map',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'center_lat' => '',
					'center_lng' => '',
					'zoom' => '',
					'height' => 300,
					'acfe_settings' => '',
					'acfe_validate' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_6ac00c91cf658',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fbe8',
			'label' => 'Buttons / Links',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69fa74648fc21',
			'label' => 'Buttons',
			'name' => 'button',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa7466c1413',
					'label' => 'Button Title',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69fa74648fc21',
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa7466c144e',
					'label' => 'Button Subtext',
					'name' => 'subtext',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69fa74648fc21',
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69fa7466c1487',
					'label' => 'Button Link',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69fa74648fc21',
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6ac00858b42c2',
			'label' => 'Scratchpad',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6ac00874b42c3',
			'label' => 'Status Sensitive Content',
			'name' => 'stat',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Hold status sensitive content here so you can just update it as needed later.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'tooltip',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Announcements & Updates',
	'show_in_rest' => 0,
	'display_title' => 'Blog Posts',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe' => array(
		'autosync' => array(
			0 => 'php',
			1 => 'json',
		),
		'advanced' => '1',
	),
	'qef_simple_location_rules' => 0,
	'acfe_categories' => array(
		'blog-posts' => 'Blog Posts',
	),
	'modified' => 1790971095,
));

endif;