<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_69a5f5706ee47',
	'title' => 'Features/Activities and Special Events Statuses',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69a61a7e8805f',
			'label' => 'Feature/ Group/ Special Event Statuses',
			'name' => 'stat',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a61a7e88060',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a61a7e88067',
					'label' => 'Features/ Activities',
					'name' => 'feature',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_feature',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'View List SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a61a7e8806a',
					'label' => 'Special Events',
					'name' => 'event',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_event',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a61a7e88065',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a61a7e88068',
					'label' => 'Featured Vendors',
					'name' => 'vendor',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'stat_vendor',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'View List SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a61a7e88069',
					'label' => 'Featured Cosplayers',
					'name' => 'cosplayer',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Coming Soon',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_69a617b6cf166',
			'label' => 'Special Events Links & Statuses',
			'name' => 'tkt',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'acfe_group_modal_close' => 0,
			'acfe_group_modal_button' => '',
			'acfe_group_modal_size' => 'large',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617b6cf17a',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => 1,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617b6cf17b',
					'label' => 'Special Event Ticket Status',
					'name' => 'sp_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_sp_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Available SOON',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 'More Info SOON',
					'prepend' => 'Status:',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617b6cf17c',
					'label' => 'Special Event Tickets Link',
					'name' => 'sp_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_sp_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 1,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617e6cf180',
					'label' => '(Column 6/12)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'columns' => '6/12',
					'endpoint' => 0,
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617b6cf17d',
					'label' => 'After Party Ticket Status',
					'name' => 'prt_stat',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'tkt_prt_stat',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'More Info SOON',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617b6cf17e',
					'label' => 'After Party Ticket Link',
					'name' => 'prt_url',
					'aria-label' => '',
					'type' => 'acfe_advanced_link',
					'instructions' => 'tkt_prt_url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_in_bindings' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => false,
					'allow_bulkedit' => false,
					'allow_quickedit' => false,
					'show_column' => false,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_69a617b6cf17f',
					'label' => '(Column Endpoint)',
					'name' => '',
					'aria-label' => '',
					'type' => 'acfe_column',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'endpoint' => 1,
					'allow_in_bindings' => 0,
					'columns' => '6/12',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'feature-options',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'display_title' => 'Features/Activities Options Page',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'qef_simple_location_rules' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1772494563,
	'acfe_categories' => array(
		'options-pages' => 'Options Pages',
	),
));

endif;